apiVersion: v1
kind: ConfigMap
metadata:
  name: assisted-service-config
  namespace: assisted-installer
  labels:
    app: assisted-service
data:
  SERVICE_BASE_URL: REPLACE_BASE_URL
  IMAGE_SERVICE_BASE_URL: REPLACE_IMAGE_SERVICE_BASE_URL
  NAMESPACE: assisted-installer
  BASE_DNS_DOMAINS: ""
  OS_IMAGES: '[{"openshift_version":"4.6","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-4.6.8-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.6/4.6.8/rhcos-live-rootfs.x86_64.img","version":"46.82.202012051820-0"},{"openshift_version":"4.7","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-4.7.33-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.7/4.7.33/rhcos-live-rootfs.x86_64.img","version":"47.84.202109241831-0"},{"openshift_version":"4.8","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-4.8.14-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.8/4.8.14/rhcos-live-rootfs.x86_64.img","version":"48.84.202109241901-0"},{"openshift_version":"4.9","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.9/4.9.0/rhcos-live-rootfs.x86_64.img","version":"49.84.202110081407-0"},{"openshift_version":"4.9","cpu_architecture":"arm64","url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-aarch64-live.aarch64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/aarch64/dependencies/rhcos/4.9/4.9.0/rhcos-4.9.0-aarch64-live-rootfs.aarch64.img","version":"49.84.202110080947-0"},{"openshift_version":"4.10","cpu_architecture":"x86_64","url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.10.0-rc.0/rhcos-4.10.0-rc.0-x86_64-live.x86_64.iso","rootfs_url":"https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/pre-release/4.10.0-rc.0/rhcos-4.10.0-rc.0-x86_64-live-rootfs.x86_64.img","version":"410.84.202202012119-0"}]'
  RELEASE_IMAGES: '[]'
  MUST_GATHER_IMAGES: '{"4.7":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5","ocs":"registry.redhat.io/ocs4/ocs-must-gather-rhel8","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8"},"4.8":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5","ocs":"registry.redhat.io/ocs4/ocs-must-gather-rhel8","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8"},"4.9":{"cnv":"registry.redhat.io/container-native-virtualization/cnv-must-gather-rhel8:v2.6.5","ocs":"registry.redhat.io/ocs4/ocs-must-gather-rhel8","lso":"registry.redhat.io/openshift4/ose-local-storage-mustgather-rhel8"}}'
  CREATE_S3_BUCKET: "true"
  ENABLE_AUTO_ASSIGN: "true"
  AUTH_TYPE: "local"
  JWKS_URL: https://api.openshift.com/.well-known/jwks.json
  OCM_BASE_URL: https://api.integration.openshift.com/
  SKIP_CERT_VERIFICATION: "true"
  PUBLIC_CONTAINER_REGISTRIES: quay.io
  CHECK_CLUSTER_VERSION: "false"
  IPV6_SUPPORT: "true"
  HW_VALIDATOR_REQUIREMENTS: '[{"version": "default", "master": {"cpu_cores": 4, "ram_mib":
    8192, "disk_size_gb": 10, "installation_disk_speed_threshold_ms": 10}, "worker":
    {"cpu_cores": 2, "ram_mib": 3072, "disk_size_gb": 10, "installation_disk_speed_threshold_ms":
    10}, "sno": {"cpu_cores": 8, "ram_mib": 32768, "disk_size_gb": 10, "installation_disk_speed_threshold_ms":
    10}}]'
  DISABLED_HOST_VALIDATIONS: ""
  DISABLED_STEPS: ""
  STORAGE: filesystem
