apiVersion: v1
kind: ServiceAccount
metadata:
  name: assisted-service
  namespace: assisted-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assisted-service
  namespace: assisted-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assisted-service
subjects:
- kind: ServiceAccount
  name: assisted-service
  namespace: assisted-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: assisted-service-leader-election-rolebinding
  namespace: assisted-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: assisted-service-leader-election-role
subjects:
- kind: ServiceAccount
  name: assisted-service
  namespace: assisted-installer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assisted-service
  namespace: assisted-installer
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
- apiGroups:
  - ""
  resourceNames:
  - assisted-service-baseiso-helper
  - assisted-service-leader-election-helper
  - assisted-service-migration-helper
  resources:
  - configmaps
  verbs:
  - get
  - update
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: assisted-service-leader-election-role
  namespace: assisted-installer
rules:
- apiGroups:
  - ""
  - coordination.k8s.io
  resources:
  - configmaps
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch